inherit: true

tools:
    external_code_coverage: true
    sensiolabs_security_checker:
        enabled: true

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
